
import java_swift
import java_awt

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class javax.swing.plaf.basic.BasicListUI$FocusHandler ///

open class BasicListUI_FocusHandler: java_swift.JavaObject, java_awt.FocusListener {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var BasicListUI_FocusHandlerJNIClass: jclass?

    /// final javax.swing.plaf.basic.BasicListUI javax.swing.plaf.basic.BasicListUI$FocusHandler.this$0

    // Skipping field: true false false false false false 

    /// public javax.swing.plaf.basic.BasicListUI$FocusHandler(javax.swing.plaf.basic.BasicListUI)

    private static var new_MethodID_1: jmethodID?

    public convenience init( this_0: BasicListUI? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: this_0, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "javax/swing/plaf/basic/BasicListUI$FocusHandler", classCache: &BasicListUI_FocusHandler.BasicListUI_FocusHandlerJNIClass, methodSig: "(Ljavax/swing/plaf/basic/BasicListUI;)V", methodCache: &BasicListUI_FocusHandler.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _this_0: BasicListUI? ) {
        self.init( this_0: _this_0 )
    }

    /// public void javax.swing.plaf.basic.BasicListUI$FocusHandler.focusGained(java.awt.event.FocusEvent)

    private static var focusGained_MethodID_2: jmethodID?

    open func focusGained( e: java_awt.FocusEvent? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: e, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "focusGained", methodSig: "(Ljava/awt/event/FocusEvent;)V", methodCache: &BasicListUI_FocusHandler.focusGained_MethodID_2, args: &__args, locals: &__locals )
    }

    open func focusGained( _ _e: java_awt.FocusEvent? ) {
        focusGained( e: _e )
    }

    /// public void javax.swing.plaf.basic.BasicListUI$FocusHandler.focusLost(java.awt.event.FocusEvent)

    private static var focusLost_MethodID_3: jmethodID?

    open func focusLost( e: java_awt.FocusEvent? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: e, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "focusLost", methodSig: "(Ljava/awt/event/FocusEvent;)V", methodCache: &BasicListUI_FocusHandler.focusLost_MethodID_3, args: &__args, locals: &__locals )
    }

    open func focusLost( _ _e: java_awt.FocusEvent? ) {
        focusLost( e: _e )
    }

    /// protected void javax.swing.plaf.basic.BasicListUI$FocusHandler.repaintCellFocus()

    private static var repaintCellFocus_MethodID_4: jmethodID?

    open func repaintCellFocus() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "repaintCellFocus", methodSig: "()V", methodCache: &BasicListUI_FocusHandler.repaintCellFocus_MethodID_4, args: &__args, locals: &__locals )
    }


}

