
import java_swift
import java_awt

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class javax.swing.plaf.FontUIResource ///

open class FontUIResource: java_awt.Font, UIResource {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var FontUIResourceJNIClass: jclass?

    /// public static final int java.awt.Font.BOLD

    // Skipping field: false true false false false false 

    /// public static final int java.awt.Font.CENTER_BASELINE

    // Skipping field: false true false false false false 

    /// public static final java.lang.String java.awt.Font.DIALOG

    // Skipping field: false true false false false false 

    /// public static final java.lang.String java.awt.Font.DIALOG_INPUT

    // Skipping field: false true false false false false 

    /// private static final int java.awt.Font.EXTRA_MASK

    /// public static final int java.awt.Font.HANGING_BASELINE

    // Skipping field: false true false false false false 

    /// public static final int java.awt.Font.ITALIC

    // Skipping field: false true false false false false 

    /// public static final int java.awt.Font.LAYOUT_LEFT_TO_RIGHT

    // Skipping field: false true false false false false 

    /// private static final int java.awt.Font.LAYOUT_MASK

    /// public static final int java.awt.Font.LAYOUT_NO_LIMIT_CONTEXT

    // Skipping field: false true false false false false 

    /// public static final int java.awt.Font.LAYOUT_NO_START_CONTEXT

    // Skipping field: false true false false false false 

    /// public static final int java.awt.Font.LAYOUT_RIGHT_TO_LEFT

    // Skipping field: false true false false false false 

    /// public static final java.lang.String java.awt.Font.MONOSPACED

    // Skipping field: false true false false false false 

    /// public static final int java.awt.Font.PLAIN

    // Skipping field: false true false false false false 

    /// private static final int java.awt.Font.PRIMARY_MASK

    /// private static final int java.awt.Font.RECOGNIZED_MASK

    /// public static final int java.awt.Font.ROMAN_BASELINE

    // Skipping field: false true false false false false 

    /// public static final java.lang.String java.awt.Font.SANS_SERIF

    // Skipping field: false true false false false false 

    /// private static final int java.awt.Font.SECONDARY_MASK

    /// public static final java.lang.String java.awt.Font.SERIF

    // Skipping field: false true false false false false 

    /// public static final int java.awt.Font.TRUETYPE_FONT

    // Skipping field: false true false false false false 

    /// public static final int java.awt.Font.TYPE1_FONT

    // Skipping field: false true false false false false 

    /// private static final java.awt.geom.AffineTransform java.awt.Font.identityTx

    /// private static final long java.awt.Font.serialVersionUID

    /// private static final float[] java.awt.Font.ssinfo

    /// private transient boolean java.awt.Font.createdFont

    /// private java.util.Hashtable java.awt.Font.fRequestedAttributes

    /// private transient java.lang.ref.SoftReference java.awt.Font.flmref

    /// private transient sun.font.Font2DHandle java.awt.Font.font2DHandle

    /// private int java.awt.Font.fontSerializedDataVersion

    /// private transient boolean java.awt.Font.hasLayoutAttributes

    /// transient int java.awt.Font.hash

    // Skipping field: true false false false false false 

    /// protected java.lang.String java.awt.Font.name

    private static var name_FieldID: jfieldID?

    override open var name: String! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "name", fieldType: "Ljava/lang/String;", fieldCache: &FontUIResource.name_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? String( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "name", fieldType: "Ljava/lang/String;", fieldCache: &FontUIResource.name_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private transient boolean java.awt.Font.nonIdentityTx

    /// private transient long java.awt.Font.pData

    /// private transient java.awt.peer.FontPeer java.awt.Font.peer

    /// protected float java.awt.Font.pointSize

    private static var pointSize_FieldID: jfieldID?

    override open var pointSize: Float {
        get {
            let __value = JNIField.GetFloatField( fieldName: "pointSize", fieldType: "F", fieldCache: &FontUIResource.pointSize_FieldID, object: javaObject )
            return __value
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( f: newValue )
            JNIField.SetFloatField( fieldName: "pointSize", fieldType: "F", fieldCache: &FontUIResource.pointSize_FieldID, object: javaObject, value: __value.f, locals: &__locals )
        }
    }

    /// protected int java.awt.Font.size

    private static var size_FieldID: jfieldID?

    override open var size: Int {
        get {
            let __value = JNIField.GetIntField( fieldName: "size", fieldType: "I", fieldCache: &FontUIResource.size_FieldID, object: javaObject )
            return Int(__value)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( i: jint(newValue) )
            JNIField.SetIntField( fieldName: "size", fieldType: "I", fieldCache: &FontUIResource.size_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected int java.awt.Font.style

    private static var style_FieldID: jfieldID?

    override open var style: Int {
        get {
            let __value = JNIField.GetIntField( fieldName: "style", fieldType: "I", fieldCache: &FontUIResource.style_FieldID, object: javaObject )
            return Int(__value)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( i: jint(newValue) )
            JNIField.SetIntField( fieldName: "style", fieldType: "I", fieldCache: &FontUIResource.style_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// private transient sun.font.AttributeValues java.awt.Font.values

    /// public javax.swing.plaf.FontUIResource(java.lang.String,int,int)

    private static var new_MethodID_1: jmethodID?

    public convenience init( name: String?, style: Int, size: Int ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        __args[0] = JNIType.toJava( value: name, locals: &__locals )
        __args[1] = jvalue( i: jint(style) )
        __args[2] = jvalue( i: jint(size) )
        let __object = JNIMethod.NewObject( className: "javax/swing/plaf/FontUIResource", classCache: &FontUIResource.FontUIResourceJNIClass, methodSig: "(Ljava/lang/String;II)V", methodCache: &FontUIResource.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _name: String?, _ _style: Int, _ _size: Int ) {
        self.init( name: _name, style: _style, size: _size )
    }

    /// public javax.swing.plaf.FontUIResource(java.awt.Font)

    private static var new_MethodID_2: jmethodID?

    public convenience init( font: java_awt.Font? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: font, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "javax/swing/plaf/FontUIResource", classCache: &FontUIResource.FontUIResourceJNIClass, methodSig: "(Ljava/awt/Font;)V", methodCache: &FontUIResource.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _font: java_awt.Font? ) {
        self.init( font: _font )
    }

}

