
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface javax.swing.text.TabableView ///

public protocol TabableView: JavaProtocol {

    /// public abstract float javax.swing.text.TabableView.getTabbedSpan(float,javax.swing.text.TabExpander)

    func getTabbedSpan( x: Float, e: TabExpander? ) -> Float

    /// public abstract float javax.swing.text.TabableView.getPartialSpan(int,int)

    func getPartialSpan( p0: Int, p1: Int ) -> Float

}


open class TabableViewForward: JNIObjectForward, TabableView {

    private static var TabableViewJNIClass: jclass?

    /// public abstract float javax.swing.text.TabableView.getTabbedSpan(float,javax.swing.text.TabExpander)

    private static var getTabbedSpan_MethodID_3: jmethodID?

    open func getTabbedSpan( x: Float, e: TabExpander? ) -> Float {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: x, locals: &__locals )
        __args[1] = JNIType.toJava( value: e, locals: &__locals )
        let __return = JNIMethod.CallFloatMethod( object: javaObject, methodName: "getTabbedSpan", methodSig: "(FLjavax/swing/text/TabExpander;)F", methodCache: &TabableViewForward.getTabbedSpan_MethodID_3, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Float(), from: __return )
    }

    open func getTabbedSpan( _ _x: Float, _ _e: TabExpander? ) -> Float {
        return getTabbedSpan( x: _x, e: _e )
    }

    /// public abstract float javax.swing.text.TabableView.getPartialSpan(int,int)

    private static var getPartialSpan_MethodID_4: jmethodID?

    open func getPartialSpan( p0: Int, p1: Int ) -> Float {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: p0, locals: &__locals )
        __args[1] = JNIType.toJava( value: p1, locals: &__locals )
        let __return = JNIMethod.CallFloatMethod( object: javaObject, methodName: "getPartialSpan", methodSig: "(II)F", methodCache: &TabableViewForward.getPartialSpan_MethodID_4, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Float(), from: __return )
    }

    open func getPartialSpan( _ _p0: Int, _ _p1: Int ) -> Float {
        return getPartialSpan( p0: _p0, p1: _p1 )
    }

}


